require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::Reporting::DeliverabilitiesController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::Reporting::Deliverability. As you add validations to Admin::Reporting::Deliverability, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "target_date" => "2013-04-05" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::Reporting::DeliverabilitiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all admin_reporting_deliverabilities as @admin_reporting_deliverabilities" do
      deliverability = Admin::Reporting::Deliverability.create! valid_attributes
      get :index, {}, valid_session
      assigns(:admin_reporting_deliverabilities).should eq([deliverability])
    end
  end

  describe "GET show" do
    it "assigns the requested admin_reporting as @admin_reporting" do
      deliverability = Admin::Reporting::Deliverability.create! valid_attributes
      get :show, {:id => deliverability.to_param}, valid_session
      assigns(:admin_reporting).should eq(deliverability)
    end
  end

  describe "GET new" do
    it "assigns a new admin_reporting as @admin_reporting" do
      get :new, {}, valid_session
      assigns(:admin_reporting).should be_a_new(Admin::Reporting::Deliverability)
    end
  end

  describe "GET edit" do
    it "assigns the requested admin_reporting as @admin_reporting" do
      deliverability = Admin::Reporting::Deliverability.create! valid_attributes
      get :edit, {:id => deliverability.to_param}, valid_session
      assigns(:admin_reporting).should eq(deliverability)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::Reporting::Deliverability" do
        expect {
          post :create, {:admin_reporting => valid_attributes}, valid_session
        }.to change(Admin::Reporting::Deliverability, :count).by(1)
      end

      it "assigns a newly created admin_reporting as @admin_reporting" do
        post :create, {:admin_reporting => valid_attributes}, valid_session
        assigns(:admin_reporting).should be_a(Admin::Reporting::Deliverability)
        assigns(:admin_reporting).should be_persisted
      end

      it "redirects to the created admin_reporting" do
        post :create, {:admin_reporting => valid_attributes}, valid_session
        response.should redirect_to(Admin::Reporting::Deliverability.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admin_reporting as @admin_reporting" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Reporting::Deliverability.any_instance.stub(:save).and_return(false)
        post :create, {:admin_reporting => { "target_date" => "invalid value" }}, valid_session
        assigns(:admin_reporting).should be_a_new(Admin::Reporting::Deliverability)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Reporting::Deliverability.any_instance.stub(:save).and_return(false)
        post :create, {:admin_reporting => { "target_date" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested admin_reporting" do
        deliverability = Admin::Reporting::Deliverability.create! valid_attributes
        # Assuming there are no other admin_reporting_deliverabilities in the database, this
        # specifies that the Admin::Reporting::Deliverability created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::Reporting::Deliverability.any_instance.should_receive(:update_attributes).with({ "target_date" => "2013-04-05" })
        put :update, {:id => deliverability.to_param, :admin_reporting => { "target_date" => "2013-04-05" }}, valid_session
      end

      it "assigns the requested admin_reporting as @admin_reporting" do
        deliverability = Admin::Reporting::Deliverability.create! valid_attributes
        put :update, {:id => deliverability.to_param, :admin_reporting => valid_attributes}, valid_session
        assigns(:admin_reporting).should eq(deliverability)
      end

      it "redirects to the admin_reporting" do
        deliverability = Admin::Reporting::Deliverability.create! valid_attributes
        put :update, {:id => deliverability.to_param, :admin_reporting => valid_attributes}, valid_session
        response.should redirect_to(deliverability)
      end
    end

    describe "with invalid params" do
      it "assigns the admin_reporting as @admin_reporting" do
        deliverability = Admin::Reporting::Deliverability.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Reporting::Deliverability.any_instance.stub(:save).and_return(false)
        put :update, {:id => deliverability.to_param, :admin_reporting => { "target_date" => "invalid value" }}, valid_session
        assigns(:admin_reporting).should eq(deliverability)
      end

      it "re-renders the 'edit' template" do
        deliverability = Admin::Reporting::Deliverability.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Reporting::Deliverability.any_instance.stub(:save).and_return(false)
        put :update, {:id => deliverability.to_param, :admin_reporting => { "target_date" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admin_reporting" do
      deliverability = Admin::Reporting::Deliverability.create! valid_attributes
      expect {
        delete :destroy, {:id => deliverability.to_param}, valid_session
      }.to change(Admin::Reporting::Deliverability, :count).by(-1)
    end

    it "redirects to the admin_reporting_deliverabilities list" do
      deliverability = Admin::Reporting::Deliverability.create! valid_attributes
      delete :destroy, {:id => deliverability.to_param}, valid_session
      response.should redirect_to(admin_reporting_deliverabilities_url)
    end
  end

end
